apiVersion: v1
kind: Service
metadata:
  name: node-lister
  namespace: default
  labels:
    app: node-lister
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: node-lister
